### ISSUE TITLE
`WriteAppend` test fails with `not_found/...` error

### ISSUE THREAD

**Issue by JinnyYi** [aos-dev/go-service-dropbox#54]
```shell
Post "https://content.dropboxapi.com/2/files/upload_session/append_v2": EOF
```

ref: https://teamcity.beyondstorage.io/buildConfiguration/Services_Dropbox_IntegrationTests/878?buildTab=log&focusLine=237&expandAll=true&logFilter=debug

**Comment by JinnyYi** [comment]
Moved to https://github.com/beyondstorage/go-storage/issues/889

**Comment by Xuanwo** [comment]
Oh, we can use GitHub "Transfer Issue" feature

![image](https://user-images.githubusercontent.com/5351546/137837015-efae5d2a-568b-4de5-b56b-0c1987cd3b7e.png)

So that we don't need to transfer them manually.
